# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OemcStac
                                 A QGIS plugin
 This plugin provides easy access to OEMC STAC catalog
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-11-07
        git sha              : $Format:%H$
        copyright            : (C) 2023 by OpenGeoHub
        email                : murat.sahin@opengeohub.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .oemc_plugin_dialog import OemcStacDialog
import os.path
import os

# iniital settings for the PYSTAC and STAC_CLIENT
from pathlib import Path
import sys
sys.path.append(str(Path(__file__).parents[0])+'/src') # findable lib path
from pystac_client.client import Client

from .task import CatalogTask, ListSelectionTask, ItemTask, AssetTask, StyleTask, registerRastersToServer
from .cache import Database

#importing the QT libs to control ui
from qgis.core import QgsProject, QgsRasterLayer, QgsTask, QgsApplication
from qgis.PyQt.QtCore import QRunnable, Qt, QThreadPool

from qgis.PyQt.QtCore import Qt, pyqtSignal
from qgis.PyQt.QtXml import QDomDocument
from qgis.PyQt.QtWidgets import QListWidget
# to access the qml files on the fly
from urllib.request import urlopen


class OemcStac:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'OemcStac_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&OEMC Plugin')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        ############################################
        # tapping on the project structure to use it
        self.project_tree = QgsProject.instance().layerTreeRoot() # QgsLayerTree()
        # saving the stac names and catalog urls as a variable
        self.main_url = None
        self.oemc_stacs = dict(
            OpenLandMap = "https://s3.eu-central-1.wasabisys.com/stac/openlandmap/catalog.json",
            EcoDataCube = "https://s3.eu-central-1.wasabisys.com/stac/odse/catalog.json"
        )
        self.task_manager = QgsApplication.taskManager()

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('OemcStac', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/oemc_plugin/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'OEMC Plugin'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&OEMC Plugin'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = OemcStacDialog()

            # creating some variable to handle the state of the plugin
            self._collection_meta = None
            self._catalog = None,
            self._all_items = None
            self._colors = None
            self._a_collection = None
            self._query_keys = dict()
            self._inserted = dict()
            self.thread_pool = QThreadPool().globalInstance()
            self.thread_pool.setMaxThreadCount(int(self.thread_pool.maxThreadCount()/2))

            # defining settings for the ui elements on the start
            self.dlg.listCatalog.view().setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
            # self.dlg.addStrategy.view().setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
            self.dlg.listItems.setSelectionMode(QListWidget.ExtendedSelection)
            self.dlg.listAssets.setSelectionMode(QListWidget.ExtendedSelection)
            # adding the stac names from oemc_stac variable
            self.dlg.listCatalog.addItem("") # extra space for visual concerns
            self.dlg.listCatalog.addItems(list(self.oemc_stacs.keys()))
            self.dlg.addLayers.setEnabled(False)

        # functionalities
        # change on the selection of the catalog will update the
        # listCatalog and fills it with the collection names
        self.dlg.listCatalog.currentIndexChanged.connect(self.catalog_task_handler)
        # based on the selection from collections this will trigered
        # following the selection this will fills the listItems
        self.dlg.listCollection.itemClicked.connect(self.taskhandler_items) 
        # this will fills the listAssets with unique assets
        self.dlg.listItems.itemClicked.connect(self.asset_task_handler)
        # this will set selected variable for seleceted assets
        self.dlg.listAssets.itemClicked.connect(self.selecting_assets)
        # this will fills the strategies wit predefined add layer strategies
        # self.dlg.addStrategy.addItems(self.strategies)
        # finally some one is going to push the addLayers button

        self.dlg.addLayers.clicked.connect(self.add_layers_in_parallel) # add_layers) # #
        self.dlg.progressBar.reset()
        self.dlg.progressBar.setTextVisible(True)
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        # result = self.dlg.exec_()
        # See if OK was pressed
        # if result:
        #     # Do something useful here - delete the line containing pass and
        #     # substitute with your code.
        #     pass
    def _clear_ui(self, params:list) -> None:
        if ('all' in params ) or ('item' in params):
            self.dlg.listItems.clear()
        
        if ('all' in params ) or ('asset' in params):
            self.dlg.listAssets.clear()
        
        if ('all' in params ) or ('collection' in params):
            self.dlg.listCollection.clear()
        
    def catalog_task_handler(self, index:int):
        """
        This function manages Catalog information in the UI.
        This function handles the contents of the collection, items, and assets.
        index: 
        """
        # clearing the UI 
        self._clear_ui(['all'])
        # disabling the add layer button
        self.dlg.addLayers.setEnabled(False)
        # setting the catalog url
        self.main_url = list(self.oemc_stacs.values())[index-1]
        
        #self.database = Database(list(self.oemc_stacs.keys())[index-1])
        #print('db connection is established')

        # registering catalog task to run in background
        # create catalog task
        access_catalog = CatalogTask(self.main_url)
        # registering
        self.task_manager.addTask(access_catalog)
       
        # handling with the results
        access_catalog.result.connect(self.listing_collection)
        access_catalog.catalogSignal.connect(self.handling_catalog)

        

    # handler function of catalog task
    def handling_catalog(self, catalog_object):
        # handles catalog
        self._catalog = catalog_object
    
    # handler of collections
    def listing_collection(self, algo_out):
        # handles the collection list in UI
        self._collection_meta = algo_out
        self.dlg.listCollection.addItems(sorted(algo_out['title']))
     
    def taskhandler_items(self):
        """
        This function manages the lists of Items and Assets
        The assets count and the naming convetions of them should be consistent
        regarding the stac specifications. To overcome the possible inconsistency 
        among them an user control flow had been added.
        """
        # clearing the items and assets for the UI
        self._clear_ui(['item','asset'])
        
        # disabling the addlayer button
        self.dlg.addLayers.setEnabled(False)
        # registering the task to scheduler

        select_collection = ListSelectionTask(self.dlg.listCollection)
        self.task_manager.addTask(select_collection)
        select_collection.result.connect(self.listing_items)
        
    # task handler function of items
    def listing_items(self, arg):
        ind = self._collection_meta['title'].index(
            sorted(self._collection_meta['title'])[arg[0]]
        )
        self._a_collection = self._collection_meta['index'][ind]

        listing_items = ItemTask(ind, self._collection_meta, self._catalog)
        self.task_manager.addTask(listing_items)
        listing_items.result.connect(self.listhandler_items)

        
    # sending item names to UI
    def listhandler_items(self, namelist):
        self.dlg.listItems.addItems(namelist)
        self._all_items = namelist

    def asset_task_handler(self):
        """
        this functions creates a task to handle with the assets information
        """
        self._clear_ui(['asset'])
        # disabling the add layer button
        self.dlg.addLayers.setEnabled(False)
        # generating a task to handle the assets
        selecting_items = ListSelectionTask(self.dlg.listItems)
        self.task_manager.addTask(selecting_items)

        # handling the task result
        selecting_items.result.connect(self.listing_assets)
        selecting_items.result.connect(self.handle_styles)
        
    # handles with selected items 
    def listing_assets(self, selectedItems):
        """
        this function generates a task to handle with the assets
        """
        self._clear_ui(['asset'])
        listing_assets = AssetTask(
            self._catalog,
            self._a_collection,
            self._all_items,
            selectedItems
        )
        self.task_manager.addTask(listing_assets)
        listing_assets.result.connect(self.listhandler_assets)

        

    def handle_styles(self, selectedItems):
        """
        this function generates a task to get the colormap of the assets
        using a function called handling_colors
        """

        style_resolver = StyleTask(self._catalog, self._a_collection, self._all_items, selectedItems)
        self.task_manager.addTask(style_resolver)
        style_resolver.result.connect(self.handling_colors)

        
    def listhandler_assets(self,givenlist):
        # asset task result handler. lists the assets in the ui and assign
        # the value to a in memory object
        self.dlg.listAssets.addItems(givenlist)
        self._all_assets = givenlist

    def handling_colors(self, given_cc):
        # asssing the the color schema to local object
        self._colors = given_cc

    # enabling the addLayers button
    def selecting_assets(self):
        self.dlg.addLayers.setEnabled(True)

    
    def add_layers_in_parallel(self):
        # implementation of registering the cloud optimized geotiffs to QGIS

        def get_selected_asset(passedArg):
            # getter for selected asset in the UI
            self._query_keys['assets'] = [self._all_assets[i] for i in passedArg]

        def get_selected_items(passedArg):
            # getter for the selected items
            self._query_keys["items"] =  [self._all_items[i] for i in passedArg]

            # settings for the progress bar 
            total_len = len(self._query_keys['assets']) * len(self._query_keys['items'])
            self.dlg.progressBar.setMaximum(total_len)
            
            # calling the registry function 
            call_parallel_implementation()
            # resseting the progress bar
            self.dlg.progressBar.reset()

        # generating the list selection task from listSelection object for assets
        select_asset = ListSelectionTask(self.dlg.listAssets)
        self.task_manager.addTask(select_asset)
        select_asset.result.connect(get_selected_asset)
        # generating the  item selection task with listSelection object
        select_item = ListSelectionTask(self.dlg.listItems)
        self.task_manager.addTask(select_item)
        select_item.result.connect(get_selected_items)

        # implementation of the registry of COGs with QRunnable
        def call_parallel_implementation():
            print(self._colors)
            print('#'*20)
            # count of the total assets that selected
            total_count = len(self._query_keys['assets']) * len(self._query_keys['items'])
            count = 0
            # setting max value of the progress bar 
            self.dlg.progressBar.setMaximum(total_count)
            """
            Logic below perfoms a check to the layerTreeRoot to see a group called `col_name`
                if the collection name exists 
                    it will perform another search for the items
                    if the item is exist it will hash the raster name to a list and registers it to QGIS
                    if the item is not exist in the hash it will hast it and insert a item tree in the layerTreeRoot 

            """
            for asset in self._query_keys['assets']:
                for pos_item, item in enumerate(self._query_keys['items']):
                    # getting the collection by using title
                    col_name = self._catalog.get_collection(self._a_collection).title
                    # looking for exist or not in the layerTreeRoot
                    col_tree = QgsProject.instance().layerTreeRoot().findGroup(col_name)
                    if col_tree: 
                        item_tree = col_tree.findGroup(item)
                        
                        if item_tree:
                            if asset not in self._inserted[self._a_collection][item]:
                                # hash the item to a list and ship to the thread
                                self._inserted[self._a_collection][item].append(asset)
                                runnable = registerRastersToServer(asset, item, self._a_collection,self._catalog, item_tree, self._colors.get(self._a_collection))
                                self.thread_pool.start(runnable)
                        else:
                            # create the item in the layerTreeRoot and ship to a thread to register 
                            item_tree = col_tree.addGroup(item)
                            self._inserted[self._a_collection][item] = [asset]

                            runnable = registerRastersToServer(asset, item, self._a_collection,self._catalog, item_tree, self._colors.get(self._a_collection))
                            self.thread_pool.start(runnable)
                        # increase the count of the progress bar
                        count += 1
                        self.dlg.progressBar.setValue(count)
                    else:
                        # create the collection in the layerTreeRoot
                        col_tree = QgsProject.instance().layerTreeRoot().addGroup(col_name)
                        item_tree = col_tree.addGroup(item)
                        # generate the hash list and insert the element
                        self._inserted[self._a_collection] = dict()
                        self._inserted[self._a_collection][item] = [asset]
                        # ship it to the thread
                        runnable = registerRastersToServer(asset, item, self._a_collection,self._catalog, item_tree, self._colors.get(self._a_collection))
                        self.thread_pool.start(runnable)
                        # set the progressbar
                        count += 1
                        self.dlg.progressBar.setValue(count)
                    
                    #collapse the item group to prevent the performance issue
                    item_tree.setExpanded(False)
                    if pos_item != 0:
                        # toggle of the inserted the item to not overload the QGIS 
                        # in default of it will try to load the layer making range request 
                        # to source of cloud native geotiff files to prevent the overload 
                        # the visibility of the layer except the first one should be setted to False
                        item_tree.setItemVisibilityChecked(False)
            # collapse the collection group
            col_tree.setExpanded(False)
